In [2]:
import numpy as np

D = [((37.5,2),1),((36,1),0),((39,1),1),((37.5,1),0),((39,0),1),((37.5,0),0),((37.5,1),0),((36,2),1)]

X = np.array([coord for coord, label in D])
y = np.array([label for coord, label in D])

In [6]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier().fit(X,y)

D_test = [((36,0),0),((37.5,1),0),((39,1),1),((39,2),0)]

X_test = np.array([coord for coord, label in D_test])
y_test = np.array([label for coord, label in D_test])

y_pred = rf.predict(X_test)
y_pred

array([0, 0, 1, 1])

In [9]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.75

In [10]:
from sklearn.metrics import f1_score

f1_score(y_test,y_pred)


0.6666666666666666

In [17]:
rf10 = RandomForestClassifier(n_estimators=10).fit(X,y)

rf10.predict(X_test)

array([0, 0, 1, 1])

In [18]:
accuracy_score(y_test, rf10.predict(X_test))

0.75

In [19]:
f1_score(y_test,rf10.predict(X_test))

0.6666666666666666

In [21]:
rf1000 = RandomForestClassifier(n_estimators=1000).fit(X,y)

rf1000.predict(X_test)

array([0, 0, 1, 1])

In [22]:
accuracy_score(y_test, rf1000.predict(X_test))

0.75

In [23]:
f1_score(y_test,rf1000.predict(X_test))

0.6666666666666666