In [1]:
import numpy as np

E = np.array([(8.5,16),(12.4,26.8),(9.3,21),(11.5,17),(17.5,25),(13,22.6),(4,16.5)])
E

array([[ 8.5, 16. ],
       [12.4, 26.8],
       [ 9.3, 21. ],
       [11.5, 17. ],
       [17.5, 25. ],
       [13. , 22.6],
       [ 4. , 16.5]])

In [10]:
# Wählen Sie k = 2 und als Initialisierungsmethode K-Means++

from sklearn.cluster import KMeans

clust = KMeans(n_clusters=2,init='k-means++').fit(E)

In [11]:
## Geben Sie die Clusterzugehörigkeiten aller Punkte an

y = clust.predict(E) 
y

array([0, 1, 0, 0, 1, 1, 0], dtype=int32)

In [12]:
clust.inertia_

69.875

In [13]:
# Geben Sie die finalen Zentroiden an

clust.cluster_centers_

array([[ 8.325, 17.625],
       [14.3  , 24.8  ]])

In [14]:
# Wählen Sie nun k = 3
clust3 = KMeans(n_clusters=3,init='k-means++').fit(E)
y = clust.predict(E) 
y

array([0, 1, 0, 0, 1, 1, 0], dtype=int32)

In [15]:
clust3.cluster_centers_.round(3)

array([[14.3  , 24.8  ],
       [ 9.767, 18.   ],
       [ 4.   , 16.5  ]])

In [16]:
clust3.inertia_

43.24666666666666